In [1]:
import itertools
from dataclasses import dataclass

import numpy as np
import numpy.typing as npt
import pandas as pd

from centrex_tlf import states, transitions, couplings, utils

from hamiltonian_utils import (
    generate_hamiltonian,
    get_transition_from_state,
    get_energies,
    sort_transitions,
    get_transitions,
)
from calibration import R0_F1_1_2_F_1, get_offset


2024-05-22 14:09:58.791 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager


In [2]:
J_ground = [0, 1, 2, 3]
J_excited = [1, 2, 3]

transitions_sorted = get_transitions(J_ground, J_excited)


2024-05-22 14:09:59.503 
  command:

    streamlit run c:\Users\ogras\anaconda3\envs\centrex-transition-finder\lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2024-05-22 14:09:59.505 No runtime found, using MemoryCacheStorageManager
c:\Users\ogras\Documents\GitHub\CeNTREX-transition-finder\hamiltonian_utils.py:124: RuntimeWarning: divide by zero encountered in scalar divide
  n_photons = 1 / br_off if 1 / br_off < 100 else 100
c:\Users\ogras\Documents\GitHub\CeNTREX-transition-finder\hamiltonian_utils.py:124: RuntimeWarning: divide by zero encountered in scalar divide
  n_photons = 1 / br_off if 1 / br_off < 100 else 100
c:\Users\ogras\Documents\GitHub\CeNTREX-transition-finder\hamiltonian_utils.py:124: RuntimeWarning: divide by zero encountered in scalar divide
  n_photons = 1 / br_off if 1 / br_off < 100 else 100
c:\Users\ogras\Documents\GitHub\CeNTREX-transition-finder\hamiltonian_utils.py:124: RuntimeWarning: divide by zero encountered in scalar divide
  n_photons = 1 / br_off 

In [3]:
reduced_hamiltonian = generate_hamiltonian(J_ground, J_excited)

In [4]:
transitions_sorted.transitions[20:40]

array([OpticalTransition(Q(3) F1'=7/2 F'=4),
       OpticalTransition(Q(2) F1'=3/2 F'=1),
       OpticalTransition(Q(3) F1'=5/2 F'=2),
       OpticalTransition(Q(3) F1'=5/2 F'=3),
       OpticalTransition(Q(2) F1'=3/2 F'=2),
       OpticalTransition(R(0) F1'=3/2 F'=1),
       OpticalTransition(R(0) F1'=3/2 F'=2),
       OpticalTransition(R(1) F1'=5/2 F'=2),
       OpticalTransition(R(1) F1'=5/2 F'=3),
       OpticalTransition(R(1) F1'=3/2 F'=1),
       OpticalTransition(R(1) F1'=3/2 F'=2),
       OpticalTransition(S(0) F1'=5/2 F'=2),
       OpticalTransition(R(2) F1'=7/2 F'=3),
       OpticalTransition(R(2) F1'=7/2 F'=4),
       OpticalTransition(S(0) F1'=3/2 F'=1),
       OpticalTransition(R(2) F1'=5/2 F'=2),
       OpticalTransition(R(2) F1'=5/2 F'=3),
       OpticalTransition(S(0) F1'=3/2 F'=2),
       OpticalTransition(S(1) F1'=7/2 F'=3),
       OpticalTransition(S(1) F1'=5/2 F'=2)], dtype=object)

In [5]:
idt = 26
df = couplings.generate_br_dataframe(
    reduced_hamiltonian.X_states,
    transitions_sorted.transitions_data[idt].states_excited,
    group_ground="J",
)
df


Js = np.array([int(df.iloc[i].name[-2]) for i in range(len(df))])
br_off = np.sum(
    [
        df.iloc[i].values
        for i in np.where(Js != transitions_sorted.transitions[idt].J_ground)[0]
    ]
)
n_photons = 1 / br_off if 1 / br_off < 100 else 100
print(transitions_sorted.transitions[idt], n_photons)
df


OpticalTransition(R(0) F1'=3/2 F'=2) 1.9218897248769047


|B, J = 1, F₁ = 3/2, F = 2>
states                                 
|X, J = 0>                     0.479679
|X, J = 2>                     0.520321

In [6]:
utils.population.thermal_population(J=np.arange(10), T=6.5)

array([0.04842538, 0.13165443, 0.1802049 , 0.18776653, 0.16282737,
       0.12164199, 0.07963084, 0.046123  , 0.02377961, 0.01095671])

In [7]:
utils.population.J_levels(2)

20

In [8]:
len(transitions_sorted.transitions_data[idt].states_ground)

15

In [14]:
transitions_sorted.transitions_data[idt].states_ground

array([1.00+0.00j x |X, J = 0, F₁ = 1/2, F = 1, mF = -1, I₁ = 1/2, I₂ = 1/2, P = +, Ω = 0>,
       1.00+0.00j x |X, J = 0, F₁ = 1/2, F = 1, mF = -1, I₁ = 1/2, I₂ = 1/2, P = +, Ω = 0>,
       1.00+0.00j x |X, J = 0, F₁ = 1/2, F = 1, mF = -1, I₁ = 1/2, I₂ = 1/2, P = +, Ω = 0>,
       1.00+0.00j x |X, J = 0, F₁ = 1/2, F = 1, mF = -1, I₁ = 1/2, I₂ = 1/2, P = +, Ω = 0>,
       1.00+0.00j x |X, J = 0, F₁ = 1/2, F = 1, mF = -1, I₁ = 1/2, I₂ = 1/2, P = +, Ω = 0>,
       1.00-0.00j x |X, J = 0, F₁ = 1/2, F = 1, mF = 0, I₁ = 1/2, I₂ = 1/2, P = +, Ω = 0>,
       1.00-0.00j x |X, J = 0, F₁ = 1/2, F = 1, mF = 0, I₁ = 1/2, I₂ = 1/2, P = +, Ω = 0>,
       1.00-0.00j x |X, J = 0, F₁ = 1/2, F = 1, mF = 0, I₁ = 1/2, I₂ = 1/2, P = +, Ω = 0>,
       1.00-0.00j x |X, J = 0, F₁ = 1/2, F = 1, mF = 0, I₁ = 1/2, I₂ = 1/2, P = +, Ω = 0>,
       1.00-0.00j x |X, J = 0, F₁ = 1/2, F = 1, mF = 0, I₁ = 1/2, I₂ = 1/2, P = +, Ω = 0>,
       1.00-0.00j x |X, J = 0, F₁ = 1/2, F = 1, mF = 1, I₁ = 1/2, I₂ = 1/2, P = +, Ω 

In [10]:
transitions_sorted.transitions_data[idt].energies

array([3237.07026026, 3237.07021062, 3237.07016099, 3237.07011135,
       3237.07006171, 3237.07026107, 3237.07021143, 3237.0701618 ,
       3237.07011216, 3237.07006253, 3237.07026188, 3237.07021224,
       3237.07016261, 3237.07011297, 3237.07006334])

In [11]:
from hamiltonian_utils import unique_unsorted

unique_unsorted(transitions_sorted.transitions_data[idt].states_ground)


[1.00+0.00j x |X, J = 0, F₁ = 1/2, F = 1, mF = -1, I₁ = 1/2, I₂ = 1/2, P = +, Ω = 0>,
 1.00-0.00j x |X, J = 0, F₁ = 1/2, F = 1, mF = 0, I₁ = 1/2, I₂ = 1/2, P = +, Ω = 0>,
 1.00-0.00j x |X, J = 0, F₁ = 1/2, F = 1, mF = 1, I₁ = 1/2, I₂ = 1/2, P = +, Ω = 0>]

In [12]:
mask_nonzero = transitions_sorted.transitions_data[idt].coupling_elements != 0

In [13]:
transitions_sorted.transitions_data[idt].states_excited[mask_nonzero]

array([0.85+0.00j x |B, J = 1, F₁ = 3/2, F = 2, mF = -2, I₁ = 1/2, I₂ = 1/2, P = -, Ω = 1>
       0.53+0.00j x |B, J = 2, F₁ = 3/2, F = 2, mF = -2, I₁ = 1/2, I₂ = 1/2, P = -, Ω = 1>
       0.01+0.00j x |B, J = 2, F₁ = 5/2, F = 2, mF = -2, I₁ = 1/2, I₂ = 1/2, P = -, Ω = 1>
       0.01+0.00j x |B, J = 3, F₁ = 5/2, F = 2, mF = -2, I₁ = 1/2, I₂ = 1/2, P = -, Ω = 1>,
       0.85+0.00j x |B, J = 1, F₁ = 3/2, F = 2, mF = -1, I₁ = 1/2, I₂ = 1/2, P = -, Ω = 1>
       0.53+0.00j x |B, J = 2, F₁ = 3/2, F = 2, mF = -1, I₁ = 1/2, I₂ = 1/2, P = -, Ω = 1>
       0.01+0.00j x |B, J = 2, F₁ = 5/2, F = 2, mF = -1, I₁ = 1/2, I₂ = 1/2, P = -, Ω = 1>
       0.01+0.00j x |B, J = 3, F₁ = 5/2, F = 2, mF = -1, I₁ = 1/2, I₂ = 1/2, P = -, Ω = 1>,
       0.85+0.00j x |B, J = 1, F₁ = 3/2, F = 2, mF = 0, I₁ = 1/2, I₂ = 1/2, P = -, Ω = 1>
       0.53+0.00j x |B, J = 2, F₁ = 3/2, F = 2, mF = 0, I₁ = 1/2, I₂ = 1/2, P = -, Ω = 1>
       0.01+0.00j x |B, J = 2, F₁ = 5/2, F = 2, mF = 0, I₁ = 1/2, I₂ = 1/2, P = -, Ω = 1>


In [18]:
for val in df:
    print(val)


|B, J = 1, F₁ = 3/2, F = 2>


In [45]:
from hamiltonian_utils import Transitions


def generate_dataframe_branching(
    transitions_interest: list[transitions.OpticalTransition],
    sorted_transitions: Transitions,
    energy_lim: tuple[float, float] = (-300, 300),
    ir_uv: str = "IR",
) -> pd.DataFrame:
    if ir_uv == "IR":
        convert = 1
    else:
        convert = 4

    indices_center = np.where(sorted_transitions.transitions == transitions_interest)[0]

    offset = sorted_transitions.energies_mean[indices_center]

    mask = ((sorted_transitions.energies_mean - offset) * convert >= energy_lim[0]) & (
        (sorted_transitions.energies_mean - offset) * convert <= energy_lim[1]
    )

    print(
        [
            [int(trans.br.iloc[i].name[-2]) for i in range(len(trans.br))]
            for trans in sorted_transitions.transitions_data[mask]
        ]
    )
    Js = np.unique(
        [
            item
            for row in [
                [int(trans.br.iloc[i].name[-2]) for i in range(len(trans.br))]
                for trans in sorted_transitions.transitions_data[mask]
            ]
            for item in row
        ]
    )

    branching = np.zeros((mask.sum(), Js.size))
    for idt, trans in enumerate(sorted_transitions.transitions_data[mask]):
        br = np.zeros(Js.shape)
        dat = [(i, int(trans.br.iloc[i].name[-2])) for i in range(len(trans.br))]
        for i, Ji in dat:
            br[np.where(Js == Ji)] = trans.br.iloc[i].values
        branching[idt] = br
    df = pd.DataFrame(
        {
            "transition": [
                trans.name for trans in sorted_transitions.transitions[mask]
            ],
        }
    )
    for idj, Ji in enumerate(Js):
        df[f"J = {Ji}"] = branching[:, idj]

    return df.set_index("transition")


In [46]:
generate_dataframe_branching(
    transitions_sorted.transitions[20],
    transitions_sorted,
)


[[0, 2], [1, 3], [0, 2], [1, 3], [2], [1, 3], [3], [0, 2], [1, 3], [1, 3], [0, 2]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (11,) + inhomogeneous part.

In [44]:
np.unique(
    np.flat(
        [
            [0, 2],
            [1, 3],
            [0, 2],
            [1, 3],
            [2],
            [1, 3],
            [3],
            [0, 2],
            [1, 3],
            [1, 3],
            [0, 2],
        ]
    )
)


AttributeError: module 'numpy' has no attribute 'flatten'